Feat/add judokas
nyx-ei/RankingList pull request #1
Opened 2024-10-18 15:11 UTC by karimalik

This PR covers the management of judokas on the admin side, with features such as: adding, deleting, editing and deleting judokas.

2024-10-26 22:31 UTC, SanAlexis requested changes
# Problèmes identifiés
* Les noms de champs qui utilisaient abusivement les majuscules.
* Des formulaires qui se répétaient
* L'usage des requêtes disséminés dans le code. C'est pratique et facile, mais ça empêche de faire des tests unitaires de qualité et surtout c'est du code trop fragile vis à vis de la bd.
* L'usage de noms de méthodes pas assez expressives vis à vis de leurs missions.

2024-10-26 22:31 UTC, SanAlexis commented on admin/partials/add-judoka.php
> +        <h3>Competition Informations</h3>
informations

2024-10-26 22:31 UTC, SanAlexis commented on admin/partials/edit-judoka.php
> +                <th><label for="full_name">Full Name</label></th>
Ce label apparait plusieurs fois. Est-ce qu'il est possible de réutiliser ce formulaire partout où on éprouve le besoin ?

2024-10-26 22:31 UTC, SanAlexis commented on includes/class-judoka-activator.php
> +        ) $charset_collate;";
Je suis absolument opposé à cette façon d'utiliser le sql dans le code PHP. Peux-tu regarder si on peut utiliser `Eloquent` ou `Propel` dans notre plugin ?

2024-10-26 22:31 UTC, SanAlexis commented on includes/class-judoka-model.php
> +    public function get_all() {
get_judokas

2024-10-26 22:31 UTC, SanAlexis commented on includes/class-judoka-model.php
> +    public function get_distinct_categories() {
Est-ce que c'est de trop ou pas ? Est-ce qu'il est possible de renvoyer des catégories qui ne soient pas distinctes avec ce type de méthodes ?

2024-10-26 22:31 UTC, SanAlexis commented on includes/class-judoka-model.php
> +    public function get_distinct_clubs() {
Même commentaire que plus haut.

2024-10-26 22:31 UTC, SanAlexis commented on includes/class-judoka-model.php
> +    public function exists($full_name, $birthday) {
judoka_exists

2024-10-31 12:10 UTC, karimalik commented on includes/class-judoka-activator.php
> +        ) $charset_collate;";
@SanAlexis j'ai regarder comment utiliser Eloquent ou Propel avec notre plugin WordPress mais un soucis, ces deux ORM nécessite une connexion sépare à la BD.  chose que je trouve qui sera pas avantageux vue qu'il peut avoir des conflit a la longue dans les màj. mais j'ai trouvé ce  package ci [wp-elonquent](https://github.com/tareq1988/wp-eloquent) qui permet d'utiliser Eloquent et le WPDB de wordpress et ne nécessitant pas de connexion supplémentaire. cependant il n'est plus maintenu depuis 6 ans déjà.

2024-11-04 21:11 UTC, SanAlexis commented on includes/class-judoka-activator.php
> +        ) $charset_collate;";
Que dit la communauté à propos ?

2024-11-05 17:35 UTC, SanAlexis approved these changes

2024-11-06 02:51 UTC, merged