Feat/edit judokas
nyx-ei/RankingList pull request #2
Opened 2024-11-01 12:06 UTC by karimalik

This PR covers the updating of judoka information

2024-11-07 05:31 UTC, SanAlexis requested changes
# Points soulevés
Les classes et les méthodes ont trop de responsabilités. C'est un constat général sur toute la PR. Une des suggestions serait de les discrétiser dans d'autres classes afin d'éviter d'avoir du code trop fragile.

2024-11-07 05:31 UTC, SanAlexis commented on admin/class-judoka-admin.php
> +        if ($this->judoka_model->judoka_exists($_POST['full_name'], $_POST['birth_date'])) {
Est-ce qu'une utilisation directe comme ça n'est pas source d'exploits de piratage ?

2024-11-07 05:31 UTC, SanAlexis commented on admin/class-judoka-admin.php
> +    public function handle_edit_judoka()
Cette méthode a trop de responsabilités:
* vérifier la nonce de sécurité;
* valider l'existence du judoka;
* valider l'intégrité et la consistance du `POST`;
* gérer l'upload de la photo de profil;
* etc.

2024-11-07 05:31 UTC, SanAlexis commented on admin/partials/add-judoka.php
> +        <?php submit_button('Add the Judoka'); ?>
```suggestion
<?php submit_button('Add the judoka'); ?>
```

2024-11-07 05:31 UTC, SanAlexis commented on admin/partials/edit-judoka.php
> +        <?php submit_button('Update the Judoka'); ?>
```suggestion
<?php submit_button('Update the judoka'); ?>
```

2024-11-07 05:49 UTC, karimalik commented on admin/class-judoka-admin.php
> +    public function handle_edit_judoka()
Je résous ceci dans la dernière PR qui est exceptionnellement dédié au refactoring.

2024-11-18 14:47 UTC, karimalik commented on admin/class-judoka-admin.php
> +    public function handle_edit_judoka()
[ici](https://github.com/nyx-ei/RankingList/pull/5/commits/87e102898d046cd0c4dff237970aff307377a317)Je résous la lourdité des différentes méthodes.

2024-11-23 06:04 UTC, merged